### ISSUE TITLE
Problème URL pour les Cartes IFR et En route

### ISSUE THREAD

**Issue by FlorentSms** [antoine1003/ChartsFinder#2]
Bonjour,

Depuis les derniers Airacs, je rencontre avec le chargement des cartes IFR et En Route:
-Pour les En Route, ils n'arrivent pas à les télécharger (le bouton E est rouge)
-Pour les cartes IFR, le bouton rond I est vert mais quand j'essaye d'ouvrir une carte, il m'ouvre une page du SIA mais le SIA indique "Page non trouvée... La page que vous avez demandé n'a pas été trouvée...".

J'ai vérifié les liens URL dans votre wiki pour les trouver et normalement c'est le bon:
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_07_DEC_2017/FRANCE/AIRAC-2017-12-07/html/index-fr-FR.html

Merci d'avance.
Bonne journée.

**Comment by antoine1003** [comment]
Salut Florent, c'est noté je vais essayé de résoudre ce problème 😄

**Comment by FlorentSms** [comment]
Salut Antoine,

Merci bien ! ;)

**Comment by antoine1003** [comment]
Tu as quelles versions du logiciel? Essaie avec les nouveaux AIRAC de janvier 
IFR : https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_04_JAN_2018/FRANCE/AIRAC-2018-01-04/html/index-fr-FR.html
VFR : https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_04_JAN_2018/Atlas-VAC/FR/VACProduitPartieframeset.htm

**Comment by FlorentSms** [comment]
Salut Antoine,

J'ai la version 3.1.2.
Avec les nouveaux airacs, ça marche parfaitement. 
Je sais pas pourquoi ça marchait pas avant, j'ai du faire une connerie mais je vois pas où.

Merci en tout cas pour tes réponses rapides.

A+
